<div class="modal w-lg fade light blur " id="addSliderModal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content card shade">
            <div class="modal-header">
                <h5 class="modal-title titr" id="exampleModalLabel">افزودن مشخصات نمایشگری جدید</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="" id="contentModal">

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn outlined o-danger c-danger" data-dismiss="modal">بستن</button>

            </div>
        </div>
    </div>
</div>
<div class="modal w-lg fade light blur " id="editSliderModal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content card shade">
            <div class="modal-header">
                <h5 class="modal-title titr" id="exampleModalLabel">ویرایش مشخصات نمایشگری</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="" id="contentModalEdit">

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn outlined o-danger c-danger" data-dismiss="modal">بستن</button>
            </div>
        </div>
    </div>
</div>
<table class="table table-striped table-bordered datatbl" id="sliderTbl" style="width:100%">
    <thead>
        <tr>
            <th>ردیف</th>
            <th>انتخاب</th>
            <th>عکس</th>
            <th>عنوان</th>
            <th>متن</th>
            <th>محصول</th>
            

        </tr>
    </thead>
    <tbody>

    </tbody>

</table>
<script>
    function deletemodal() {
        if ($(':radio[name="choicedslider"]').is(':checked')) {
 
            bootbox.confirm({
                message: "  برای حذف مطمئن هستید؟", locale: 'fa', callback: function (result) {
                    if (result) {
                        $.ajax({
                            url: "/Setting/Mngslider/deleteslider",
                            method: "POST",
                            data: {'<?php
                  $detailinputname = array ('name' => "ID_SLIDER", 'title' => "انتخاب نمایشگر", 'required' => 1,'encrypt' => 1);
                 echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>': $(':radio[name="choicedslider"]:checked').val() },
                        })
                            .done(function (res) {
                                var result=JSON.parse(res);
                                if(result.flag){
                                    toastr.success(result.msg, "عملیات حذف مشخصات نمایشگری", { timeOut: 10000 });
                                    var table = $('#sliderTbl').DataTable().ajax.reload();
                                }
                                else{
                                    toastr.error(result.msg, "عملیات حذف مشخصات نمایشگری", { timeOut: 10000 });
                                }                       

                            });
                    }
                }
            });

        }
        else {
            bootbox.alert({ message: 'نمایشگر مورد نظر برای حذف را انتخاب کنید', locale: 'fa' });
        }
    }
    $(document).ready(function () {
        $('.datatbl').DataTable(
            {
                "language":
                {
                    url: '/dist/fa.json',
                },
                processing: true,
                serverSide: true,
                autowidth: false,
                columns: [
                    { "width": "80px" },
                    { "width": "80px" },
                    { "width": "80px" }, null, null, null
                ],
                ajax: '<?php echo $this->baseUrl() ?>/Setting/Mngslider/getsliderlist',
                paging: true,
                lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'همه']],
            });
        $('#addSliderModal').on('show.bs.modal', function () {
            GetContent('<?php echo $this->baseUrl() ?>/Setting/Mngslider/Addslider', '#contentModal');

        });
        $('#editSliderModal').on('show.bs.modal', function (e) {
            if ($(':radio[name="choicedslider"]').is(":checked")) {
                GetContent('<?php echo $this->baseUrl() ?>/Setting/Mngslider/editslider', '#contentModalEdit',
                 {'<?php
                  $detailinputname = array ('name' => "ID_SLIDER", 'title' => "انتخاب نمایشگر", 'required' => 1,'encrypt' => 1);
                 echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>': $(':radio[name="choicedslider"]:checked').val()
                 }
                );
            }
            else {
                $('#contentModalEdit').html('<span class="alert alert-warning">نمایشگر مورد نظر برای ویرایش را انتخاب کنید</span>');
            }

        });

    });
</script>