<div class="modal w-lg fade light blur " id="addCarModal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content card shade">
            <div class="modal-header">
                <h5 class="modal-title titr" id="exampleModalLabel">افزودن مشخصات گروه خودروی جدید</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="" id="contentModal">

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn outlined o-danger c-danger" data-dismiss="modal">بستن</button>

            </div>
        </div>
    </div>
</div>
<div class="modal w-lg fade light blur " id="editCarModal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content card shade">
            <div class="modal-header">
                <h5 class="modal-title titr" id="exampleModalLabel">ویرایش مشخصات گروه خودروی</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="" id="contentModalEdit">

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn outlined o-danger c-danger" data-dismiss="modal">بستن</button>
            </div>
        </div>
    </div>
</div>
<table class="table table-striped table-bordered datatbl" id="carTbl" style="width:100%">
    <thead>
        <tr>
            <th>ردیف</th>
            <th>انتخاب</th>
            <th>عنوان</th>
            <th>سازنده</th>
            <th>مدل</th>
            <th>گروه</th>
            <th>سال تولید</th>
            

        </tr>
    </thead>
    <tbody>

    </tbody>

</table>
<script>
    function deletemodal() {
        if ($(':radio[name="choicedcar"]').is(':checked')) {
 
            bootbox.confirm({
                message: "  برای حذف مطمئن هستید؟", locale: 'fa', callback: function (result) {
                    if (result) {
                        $.ajax({
                            url: "/Setting/Mngcar/deletecar",
                            method: "POST",
                            data: {'<?php
                  $detailinputname = array ('name' => "ID_CARGROUP", 'title' => "انتخاب گروه خودرو", 'required' => 1,'encrypt' => 1);
                 echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>': $(':radio[name="choicedcar"]:checked').val() },
                        })
                            .done(function (res) {
                                var result=JSON.parse(res);
                                if(result.flag){
                                    toastr.success(result.msg, "عملیات حذف مشخصات گروه خودروی", { timeOut: 10000 });
                                    var table = $('#carTbl').DataTable().ajax.reload();
                                }
                                else{
                                    toastr.error(result.msg, "عملیات حذف مشخصات گروه خودروی", { timeOut: 10000 });
                                }                       

                            });
                    }
                }
            });

        }
        else {
            bootbox.alert({ message: 'گروه خودرو مورد نظر برای حذف را انتخاب کنید', locale: 'fa' });
        }
    }
    $(document).ready(function () {
        $('.datatbl').DataTable(
            {
                "language":
                {
                    url: '/dist/fa.json',
                },
                processing: true,
                serverSide: true,
                autowidth: false,
                columns: [
                    { "width": "80px" },
                    { "width": "80px" },
                    { "width": "80px" }, null, null, null,null
                ],
                ajax: '<?php echo $this->baseUrl() ?>/Setting/Mngcar/getcarlist',
                paging: true,
                lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'همه']],
            });
        $('#addCarModal').on('show.bs.modal', function () {
            GetContent('<?php echo $this->baseUrl() ?>/Setting/Mngcar/Addcar', '#contentModal');

        });
        $('#editCarModal').on('show.bs.modal', function (e) {
            if ($(':radio[name="choicedcar"]').is(":checked")) {
                GetContent('<?php echo $this->baseUrl() ?>/Setting/Mngcar/editcar', '#contentModalEdit',
                 {'<?php
                  $detailinputname = array ('name' => "ID_CARGROUP", 'title' => "انتخاب گروه خودرو", 'required' => 1,'encrypt' => 1);
                 echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>': $(':radio[name="choicedcar"]:checked').val()
                 }
                );
            }
            else {
                $('#contentModalEdit').html('<span class="alert alert-warning">گروه خودرو مورد نظر برای ویرایش را انتخاب کنید</span>');
            }

        });

    });
</script>