<?php 
$translate=Zend_Registry::get('Zend_Translate');
?>
<!doctype html>
<html class="no-js" lang="">

<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title><?php echo $this->translate('welcome'); ?></title>
	<meta name="google-site-verification" content="" />
	<meta name="description" content="<?php //echo $translate('welcome'); ?>">
	<meta name=”robots” content="index, follow">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->baseUrl() ?>/img/favicon/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->baseUrl() ?>/img/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="<?php echo $this->baseUrl() ?>/img/favicon/favicon-16x16.png">
	<link rel="manifest" href="<?php echo $this->baseUrl() ?>/img/favicon/site.webmanifest">
	<link rel="mask-icon" href="<?php echo $this->baseUrl() ?>/img/favicon/safari-pinned-tab.svg" color="#5bbad5">
	<meta name="msapplication-TileColor" content="#2b5797">
	<meta name="theme-color" content="#ffffff">
	<!-- Place favicon.ico in the root directory -->
	<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/normalize.css">
	<link href="<?php echo $this->baseUrl() ?>/css/fontawsome/all.min.css" rel="stylesheet">
	<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/bootstrap-material-design.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/dataTables.bootstrap4.css">
	<link href="<?php echo $this->baseUrl() ?>/css/toastr.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/animate.min.css" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/main.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/select2.min.css">
	 <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/bootstrap-datepicker.min.css" />
	 <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/sweetalert2.min.css" />
	
	<link rel="stylesheet/less" href="<?php echo $this->baseUrl() ?>/less/bootstrap-checkbox-tree.less"
		type="text/css" />
	<script src="<?php echo $this->baseUrl() ?>/js/jquery-3.2.1.min.js"></script>
</head>
<?php $authNamespace = Zend_Registry::get("authNamespace");?>
<body class="rtl persianumber">

	<div class="bmd-layout-container bmd-drawer-f-l avam-container animated bmd-drawer-in">

		<header class="bmd-layout-header ">
			<div class="navbar navbar-light bg-faded animate__animated animate__fadeInDown">

				<button class="navbar-toggler animate__animated animate__wobble animate__delay-2s" type="button"
					data-toggle="drawer" data-target="#dw-s1">
					<span class="navbar-toggler-icon"></span>
					<!-- <i class="material-Animation">menu</i> -->
				</button>

				<ul class="nav navbar-nav ">

					<li class="nav-item">
						<div class="dropdown">
							<button class="btn  dropdown-toggle m-0" type="button" id="dropdownMenu3"
								data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="far fa-bell  fa-lg "></i><span
									class="badge badge-pill badge-warning animate__animated animate__flash animate__repeat-3 animate__slower animate__delay-2s">5</span>
							</button>
							<div aria-labelledby="dropdownMenu2"
								class="dropdown-menu dropdown-menu-right dropdown-menu dropdown-menu-right-lg">
								<span class="dropdown-item dropdown-header">15 هشدار</span>
								<div class="dropdown-divider"></div>
								<a href="#" class="dropdown-item">
									<i class="far fa-envelope c-main mr-2"></i> 4 پیغام جدید
									<span class="float-right-rtl text-muted text-sm">3 </span>
								</a>
								<div class="dropdown-divider"></div>
								<a href="#" class="dropdown-item">
									<i class="far fa-user c-main mr-2"></i> 8 درخواست ثبت نام
									<span class="float-right-rtl text-muted text-sm">12 ساعت</span>
								</a>

								<div class="dropdown-divider"></div>
								<a href="#" class="dropdown-item dropdown-footer">مشاهده همه هشدارها</a>
							</div>
						</div>
					</li>
					<li class="nav-item"> <img src="<?php echo $this->baseUrl() ?>/img/person/<?php echo  $authNamespace->personid;?>.jpg" alt="..."
							class="rounded-circle screen-user-profile"></li>
					<li class="nav-item">
						<div class="dropdown">
							<button class="btn  dropdown-toggle m-0" type="button" id="dropdownMenu4"
								data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<?php
								echo $authNamespace->name;
								?>
							</button>
							<div aria-labelledby="dropdownMenu4"
								class="dropdown-menu dropdown-menu-right dropdown-menu dropdown-menu-right"
								aria-labelledby="dropdownMenu2">
								<button class="dropdown-item" type="button"><i
										class="far fa-user fa-sm c-main mr-2"></i>مشخصات فردی</button>
								<button onclick="dark()" class="dropdown-item" type="button"><i
										class="fas fa-moon fa-sm c-main mr-2"></i>تغییر تم</button>
								<button class="dropdown-item" type="button"><i
										class="fas fa-cog fa-sm c-main mr-2"></i>تنظیمات</button>
								<button class="dropdown-item" onclick="location.href='/index/logout'" type="button"><i
										class="fas fa-sign-out-alt c-main fa-sm mr-2"></i>خروج</button>
							</div>
						</div>
					</li>
					<li class="nav-item">
						<span
							class="animate__animated animate__flash animate__repeat-3 animate__slower animate__delay-2s">
							<?php echo $this->sitemap ?>
						</span>
					</li>
				</ul>

			</div>
		</header>
		<div id="dw-s1" class="bmd-layout-drawer bg-faded">

			<div class="container-fluid side-bar-container">
				<header class="pb-0" style="background: #f60808fc;margin: 2px;border-radius: 20px;">
					<a class="navbar-brand">
						 <img src="./svg/tire.svg" alt="..." class="mw-center">
						 
					</a>
				</header>
				<?php
				echo Application_Model_Func_Function::getMenu();
				?>
			</div>
		</div>
		<main class="bmd-layout-content">
			<div class="container-fluid ">
				<div id="presentation" class="box-card-content">
					<?php
					if (isset($this->toolbars) && count($this->toolbars) > 0) {
						?>
						<div class="row" style="direction:ltr;margin-bottom: 10px;">
							<header class="">
								<div class="navbar  bg-faded animate__animated animate__fadeInDown">
									<ul class="nav navbar-nav ">
										<?php
										foreach ($this->toolbars as $keytools => $tools):
											?>
											<li class="nav-item">
												<?php
												echo $tools;
												?>
											</li>

											<?php
										endforeach;
										?>
									</ul>
								</div>
							</header>
						</div>
						<?php
					}
					echo $this->layout()->content;
					?>
				</div>
			</div>
		</main>
	</div>





	<script src="<?php echo $this->baseUrl() ?>/js/vendor/modernizr.js"></script>

	<script>
		window.jQuery || document.write('<script src="<?php echo $this->baseUrl() ?>/js//vendor/jquery-3.2.1.min.js"><\/script>')
	</script>
	<script src="<?php echo $this->baseUrl() ?>/js/popper.js">
	</script>
	<script src="<?php echo $this->baseUrl() ?>/js/toastr.min.js"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/bootstrap-material-design.js">
	</script>
	<script src="<?php echo $this->baseUrl() ?>/js/chart.js"></script>
	<script>
		$(document).ready(function () {
			$('body').bootstrapMaterialDesign();
		});
	</script>

	<script src="<?php echo $this->baseUrl() ?>/js/main.js"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/bootstrap.min.js"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/dataTables.js"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/dataTables.bootstrap4.js"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/select2.min.js"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/bootstrap-datepicker.min.js"></script>
    <script src="<?php echo $this->baseUrl() ?>/js/bootstrap-datepicker.fa.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/bootstrap-checkbox-tree.js"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/sweetalert2.js"></script>
	<script src="<?php echo $this->baseUrl() ?>/js/bootbox.all.min.js"></script>
	<?php
	if (is_array($this->msg)) {
		?>
		<script>
			toastr.<?php echo $this->msg['code'] ?>('<?php echo $this->msg['message'] ?>', '<?php echo $this->msg['title'] ?>', { timeOut: 10000 });
		</script>
		<?php
	}
	?>
</body>

</html>