

<div class="row  m-1 pb-4 mb-3 ">
			<div class="col-xs-12  col-sm-12  col-md-12  col-lg-12 p-2">
				<div class="page-header breadcrumb-header ">
					<div class="row align-items-end ">
						<div class="col-lg-8">
							<div class="page-header-title text-left-rtl">
								<div class="d-inline">
									<h3 class="lite-text "><?php echo $this->translate('dashboard_sys')?></h3>
									
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item "><a href="#"><i class="fas fa-home"></i></a></li>
								<li class="breadcrumb-item active"><?php echo $this->translate('dashboard')?></li>
							</ol>
						</div>
					</div>
				</div>
			</div>
		</div>
		<hr class="hr-dashed">
		<div class="row mb-2">
	
			<div class="col-xl-3 col-md-6 col-sm-6 p-2">
				<button class="btn btn-default">
				<div class="box-card mini animate__animated animate__flipInY   "><i class=" far  	fas fa-chair b-forth"
						aria-hidden="true"></i>
					<span class="c-forth"><?php echo $this->translate('call_crisis')?></span>
				
					
				</div>
</button>
			</div>
		</div>
		
