
<div class="modal w-lg fade light blur " id="addGroupModal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content card shade">
            <div class="modal-header">
                <h5 class="modal-title titr" id="exampleModalLabel">افزودن گروه جدید</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="" id="contentModal">

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn outlined o-danger c-danger" data-dismiss="modal">بستن</button>
            </div>
        </div>
    </div>
</div>
<div class="modal w-lg fade light blur " id="editGroupModal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content card shade">
            <div class="modal-header">
                <h5 class="modal-title titr" id="exampleModalLabel">ویرایش گروه</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="" id="contentModalEdit">

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn outlined o-danger c-danger" data-dismiss="modal">بستن</button>
            </div>
        </div>
    </div>
</div>
<table id="" class="table table-striped table-bordered datatbl" id="groupTbl" style="width:100%">
    <thead>
        <tr>
            <th width="50px">ردیف</th>
            <th>انتخاب</th>
            <th>نام گروه</th>
        </tr>
    </thead>
    <tbody>

    </tbody>

</table>
<script>
        function deletemodal() {
        if ($(':radio[name="choicedgroup"]').is(':checked')) {
 
            bootbox.confirm({
                message: "  برای حذف مطمئن هستید؟", locale: 'fa', callback: function (result) {
                    if (result) {
                        $.ajax({
                            url: "/User/Mnggroup/deletegroup",
                            method: "POST",
                            data: {'<?php
                  $detailinputname = array ('name' => "ID", 'title' => "انتخاب شخص", 'required' => 1,'encrypt' => 1);
                 echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>': $(':radio[name="choicedgroup"]:checked').val() },
                        })
                            .done(function (res) {
                                var result=JSON.parse(res);
                                if(result.flag){
                                    toastr.success(result.msg, "عملیات حذف گروه کاربری ", { timeOut: 10000 });
                                    location.reload();
                                }
                                else{
                                    toastr.error(result.msg, "عملیات حذف گروه کاربری ",  { timeOut: 10000 });
                                }                       

                            });
                    }
                }
            });

        }
        else {
            bootbox.alert({ message: 'گروه مورد نظر برای حذف را انتخاب کنید', locale: 'fa' });
        }
    }

    $(document).ready(function () {
        $('.datatbl').DataTable(
            {
                "language":
                {
                    url: '/dist/fa.json',
                },
                processing: true,
                serverSide: true,
                autowidth: false,
                columns: [
                    { "width": "80px" },
                    { "width": "80px" },
                    null
                ],
                ajax: {
                    url:'<?php echo $this->baseUrl() ?>/User/Mnggroup/getgrouplist',
                    error:function(xhr,error,thrown){
                                    toastr.error('خطا در دریافت اطلاعات پیش آمده است لطفا با پشتیبانی تماس بگیرید.', 'خطا در سمت سرور', { timeOut: 50000 });
                            }
                        },
                paging: true,
                lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'همه']],
            });
        $('#addGroupModal').on('show.bs.modal', function () {
            GetContent('<?php echo $this->baseUrl() ?>/User/Mnggroup/addgroup', '#contentModal');

        });
        $('#editGroupModal').on('show.bs.modal', function (e) {
            if ($(':radio[name="choicedgroup"]:checked').length > 0) {
                GetContent('<?php echo $this->baseUrl() ?>/User/Mnggroup/editgroup', '#contentModalEdit',
                {'<?php
                  $detailinputname = array ('name' => "ID", 'title' => "انتخاب گروه", 'required' => 1,'encrypt' => 1);
                 echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>': $(':radio[name="choicedgroup"]:checked').val()
                 }
            );
            }
            else {
                $('#contentModalEdit').html('<span>گروه مورد نظر برای ویرایش را انتخاب کنید<span>');
            }

        });
    });
</script>