
<form role="form" class="frm" method="POST" enctype="multipart/form-data"
    action="<?php $this->baseUrl() ?>/User/Mngperson/Saveperson" id="frmAddPerson">
    <?php
 
    if (isset($this->toolbars)) {
        ?>
        <div class="row" style="direction:ltr;margin-bottom: 10px;">
            <header class="">
                <div class="animate__animated animate__fadeInDown">
                    <ul class="nav navbar-nav ">

                        <?php
                        foreach ($this->toolbars as $keytools => $tools):
                            ?>
                            <li class="nav-item">
                                <?php
                                echo $tools;
                                ?>
                            </li>

                            <?php
                        endforeach;
                        ?>


                    </ul>
                </div>
            </header>
        </div>
        <?php
    }
    ?>
    <?php
    if (isset($this->ID)):
        ?>
        <input name="<?php
        $detailinputname = array('name' => "ID_PERSON", 'title' => "شماره اختصاصی", 'required' => 1, 'encrypt' => 1);
        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
        ?>" type="hidden"
            value="<?php echo base64_encode(Application_Model_Func_Crypt::Encrypt($this->PERSON['ID_PERSON'])) ?>" />
        <?php
    endif
    ?>
    <?php
    if (isset($this->ID)):
        ?>
        <input name="<?php
        $detailinputname = array('name' => "ID_ADDRESS", 'title' => "شماره  اختصاصی آدرس", 'required' => 1, 'encrypt' => 1);
        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
        ?>" type="hidden"
            value="<?php echo base64_encode(Application_Model_Func_Crypt::Encrypt($this->PERSON['ID_ADDRESS'])) ?>" />
        <?php
    endif
    ?>
        <?php
    if (isset($this->ID)):
        ?>
        <input name="<?php
        $detailinputname = array('name' => "ID_CARGROUPITEM", 'title' => "شماره  اختصاصی خورویی", 'required' => 1, 'encrypt' => 1);
        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
        ?>" type="hidden"
            value="<?php echo base64_encode(Application_Model_Func_Crypt::Encrypt($this->PERSON['ID_CARGROUPITEM'])) ?>" />
        <?php
    endif
    ?>
    <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="Name_PERSON">نام <span class="required">*</span></label>
                <input type="text" class="form-control" value="<?php
                if (isset($this->PERSON)):
                    echo $this->PERSON['NAME_PERSON'];
                endif;
                ?>" id="Name_PERSON" name="<?php
                $detailinputname = array('name' => "NAME_PERSON", 'title' => "نام شخص", 'required' => 1);
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" required='required' placeholder="نام شخص را وارد کنید">
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="famil">فامیل <span class="required">*</span></label>
                <input type="text" class="form-control" value="<?php
                if (isset($this->ID)):
                    echo $this->PERSON['FAMIL'];
                endif;
                ?>" id="famil" name="<?php
                $detailinputname = array('name' => "FAMIL", 'title' => "فامیل شخص", 'required' => 1);
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" required='required' placeholder="نام خانوادگی را وارد کنید">
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="codemeli">کد ملی <span class="required">*</span></label>
                <input type="number" class="form-control" value="<?php
                if (isset($this->ID)):
                    echo $this->PERSON['CODEMELI'];
                endif;
                ?>" id="codemeli" max="9999999999" maxlength="10" min="0" name="<?php
                $detailinputname = array('name' => "CODEMELI", 'title' => "کد ملی شخص", 'required' => 1);
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" required='required' placeholder="شماره ملی را وارد کنید">
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="mobile">موبایل <span class="required">*</span></label>
                <input type="text" class="form-control" value="<?php
                if (isset($this->ID)):
                    echo $this->PERSON['MOBILE'];
                endif;
                ?>" id="mobile" name="<?php
                $detailinputname = array('name' => "MOBILE", 'title' => "موبایل شخص", 'required' => 1);
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" required='required' placeholder="شماره موبایل را وارد کنید">
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="tel">تلفن ثابت <span class="required">*</span></label>
                <input type="text" class="form-control" value="<?php
                if (isset($this->ID)):
                    echo $this->PERSON['TEL'];
                endif;
                ?>" id="tel" name="<?php
                $detailinputname = array('name' => "TEL", 'title' => "تلفن شخص", 'required' => 1);
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" required='required' placeholder="شماره تلفن ثابت را وارد کنید">
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="email">ایمیل </label>
                <input type="email" class="form-control" value="<?php
                if (isset($this->ID)):
                    echo $this->PERSON['EMAIL'];
                endif;
                ?>" id="email" name="<?php
                $detailinputname = array('name' => "EMAIL", 'title' => "ایمیل شخص", 'required' => 0);
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" placeholder="آدرس ایمیل را وارد کنید">
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <fieldset style="border:solid 1px gray">
                <legend style="border: solid 1px gray;
                                background: gray;
                                font-family: BTitr;
                                font-size: 20px;">آدرس</legend>

                <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
                    <div class="form-group">
                        <label for="stateid">استان <span class="required">*</span></label>
                        <select class="form-control"  id="stateid" name="<?php
                        $detailinputname = array(
                            'name' => "PROVINCE",
                            'title' => "استان محل سکونت ",
                            'required' => 1,
                            'encrypt' => 1
                        );
                        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                        ?>" required='required' placeholder="استان محل سکونت را وارد کنید">
                            <option></option>
                            <?php
                            $personProvince=base64_encode(Application_Model_Func_Crypt::Encrypt($this->PERSON['PROVINCE']));
                            foreach ($this->provinces as $province) {
                                ?>
                                <option <?php
                                if ( $personProvince== $province['CODE']) {
                                    echo "selected";
                                }
                                ?>
                                    value='<?php echo $province['CODE'] ?>'><?php echo $province['CATNAME'] ?>
                                </option>
                                <?php
                            }
                            ?>

                        </select>
                    </div>
                </div>
                <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
                    <div class="form-group">
                        <label for="cityid">شهرستان <span class="required">*</span></label>
                        <select type="text" class="form-control"  id="cityid" name="<?php
                        $detailinputname = array('name' => "CITY", 'title' => "شهرستان محل سکونت ", 'required' => 1, 'encrypt' => 1);
                        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                        ?>" required='required' placeholder="شهرستان محل سکونت را وارد کنید">
                            <option>
                            </option>
                        </select>
                    </div>
                </div>
                <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
                    <div class="form-group">
                        <label for="codepost">کد پستی <span class="required">*</span></label>
                        <input type="text" class="form-control" value="<?php
                        if (isset($this->PERSON)):
                            echo $this->PERSON['POSTCODE'];
                        endif;
                        ?>" id="codepost" name="<?php
                        $detailinputname = array('name' => "POSTCODE", 'title' => "کدپستی را وارد کنید", 'required' => 1);
                        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                        ?>" required='required' placeholder="کدپستی را وارد کنید">
                    </div>
                </div>
                <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                    <div class="form-group">
                        <label for="address">آدرس <span class="required">*</span></label>
                        <input type="text" class="form-control" value="<?php
                        if (isset($this->PERSON)):
                            echo $this->PERSON['ADDRTEXT'];
                        endif;
                        ?>" id="address" name="<?php
                        $detailinputname = array('name' => "ADDRTEXT", 'title' => "ادرس شخص", 'required' => 1);
                        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                        ?>" required='required' placeholder="آدرس را وارد کنید">
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <fieldset style="border:solid 1px gray">
                <legend style="border: solid 1px gray;
                                background: gray;
                                font-family: BTitr;
                                font-size: 20px;">مشخصات خودرو</legend>

                <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
                    <div class="form-group">
                        <label for="stateid">گروه خودرویی <span class="required">*</span></label>
                        <select class="form-control"  id="cargroup" name="<?php
                        $detailinputname = array(
                            'name' => "CARGROUPID",
                            'title' => "گروه خودرویی",
                            'required' => 1,
                            'encrypt' => 1
                        );
                        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                        ?>" required='required' placeholder="گروه خودرویی را وارد کنید">
                            <option></option>
                            <?php
                            $personCargroup=base64_encode(Application_Model_Func_Crypt::Encrypt($this->PERSON['CARGROUPID']));
                            foreach ($this->cargroups as $cargroup) {
                                ?>
                                <option <?php
                                if ( $personCargroup== $cargroup['ID_CARGROUP']) {
                                    echo "selected";
                                }
                                ?>
                                    value='<?php echo $cargroup['ID_CARGROUP'] ?>'><?php echo $cargroup['NAME_CARGROUP'] ?>
                                </option>
                                <?php
                            }
                            ?>

                        </select>
                    </div>
                </div>
                
                <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
                    <div class="form-group">
                        <label for="transit">مسیر حمل و نقلی  </label>
                        <textarea  class="form-control"  id="transit" name="<?php
                        $detailinputname = array('name' => "TRANSIT", 'title' => "مسیر حمل و نقل را وارد کنید", 'required' => 0);
                        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                        ?>" required='required' placeholder="مسیر حمل و نقلی  را وارد کنید"><?php   if (isset($this->PERSON)):
                            echo $this->PERSON['TRANSIT'];
                        endif;
                        ?></textarea>
                    </div>
                </div>
               
            </fieldset>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="avatar">عکس پروفایل </label>
                <input type="file" class="form-control" id="avatar" name="<?php
                $detailinputname = array('name' => "AVATAR", 'title' => "عکس پروفایل شخص", 'required' => 0, 'filetype' => array('image/png', 'image/jpeg'), 'volumfile' => '500000');
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" placeholder="عکس پرسنلی را بارگزاری کنید">
            </div>
        </div>

    </div>

</form>
<script>
    function getData( $province){
        var optionList = [];
            var personcity='<?php echo base64_encode(Application_Model_Func_Crypt::Encrypt($this->PERSON['CITY']));?>';
            var selected='';
            $.post('<?php echo $this->baseUrl() ?>/Coding/Mngcoding/getcity', { 'province': $province}, function (result, status) {
                $('#cityid').find('option').remove();
                $.each(result, function (index, elm) {
                    if(elm['SUBCODE']==personcity){
                        selected='selected';
                    }
                    else{
                        selected=''; 
                    }
                    $('#cityid').find('option').end().append('<option '+selected+' value="' + elm['SUBCODE'] + '">' + elm['SUBCATNAME'] + '</option>');
                });
            }, 'json');
    }
    $(document).ready(function () {
        var province='<?php echo base64_encode(Application_Model_Func_Crypt::Encrypt($this->PERSON['PROVINCE']))?>';
        if(province!=''){
            getData(province);
        }
        $('#stateid').on('change', function () {
           getData($(this).val());
        });
        $('*[required]').attr('oninvalid', "this.setCustomValidity('این فیلد نباید خالی باشد.')");
        $('*[required]').attr('oninput', "this.setCustomValidity('')");

    });
</script>