
<form role="form" class="frm" method="POST" enctype="multipart/form-data"
    action="<?php $this->baseUrl() ?>/User/Mngcompany/Savecompany" id="frmAddCompany">
    <?php
 
    if (isset($this->toolbars)) {
        ?>
        <div class="row" style="direction:ltr;margin-bottom: 10px;">
            <header class="">
                <div class="animate__animated animate__fadeInDown">
                    <ul class="nav navbar-nav ">

                        <?php
                        foreach ($this->toolbars as $keytools => $tools):
                            ?>
                            <li class="nav-item">
                                <?php
                                echo $tools;
                                ?>
                            </li>

                            <?php
                        endforeach;
                        ?>


                    </ul>
                </div>
            </header>
        </div>
        <?php
    }
    ?>
    <?php
    if (isset($this->ID)):
        ?>
        <input name="<?php
        $detailinputname = array('name' => "ID_COMPANY", 'title' => "شماره اختصاصی", 'required' => 1, 'encrypt' => 1);
        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
        ?>" type="hidden"
            value="<?php echo base64_encode(Application_Model_Func_Crypt::Encrypt($this->COMPANY['ID_COMPANY'])) ?>" />
        <?php
    endif
    ?>
    <?php
    if (isset($this->ID)):
        ?>
        <input name="<?php
        $detailinputname = array('name' => "ID_ADDRESS", 'title' => "شماره  اختصاصی آدرس", 'required' => 1, 'encrypt' => 1);
        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
        ?>" type="hidden"
            value="<?php echo base64_encode(Application_Model_Func_Crypt::Encrypt($this->COMPANY['ID_ADDRESS'])) ?>" />
        <?php
    endif
    ?>

    <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="Name_COMPANY">نام شرکت <span class="required">*</span></label>
                <input type="text" class="form-control" value="<?php
                if (isset($this->COMPANY)):
                    echo $this->COMPANY['NAME_COMPANY'];
                endif;
                ?>" id="Name_COMPANY" name="<?php
                $detailinputname = array('name' => "NAME_COMPANY", 'title' => "نام شرکت", 'required' => 1);
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" required='required' placeholder="نام شرکت را وارد کنید">
            </div>
        </div>
      
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="codemeli">شناسه ملی <span class="required">*</span></label>
                <input type="number" class="form-control" value="<?php
                if (isset($this->ID)):
                    echo $this->COMPANY['CODEMELI'];
                endif;
                ?>" id="codemeli" max="9999999999" maxlength="10" min="0" name="<?php
                $detailinputname = array('name' => "CODEMELI", 'title' => "کد ملی شرکت", 'required' => 1);
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" required='required' placeholder="شناسه ملی را وارد کنید">
            </div>
        </div>
      
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="tel">تلفن ثابت <span class="required">*</span></label>
                <input type="text" class="form-control" value="<?php
                if (isset($this->ID)):
                    echo $this->COMPANY['TEL'];
                endif;
                ?>" id="tel" name="<?php
                $detailinputname = array('name' => "TEL", 'title' => "تلفن شرکت", 'required' => 1);
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" required='required' placeholder="شماره تلفن ثابت را وارد کنید">
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
            <div class="form-group">
                <label for="email">ایمیل </label>
                <input type="email" class="form-control" value="<?php
                if (isset($this->ID)):
                    echo $this->COMPANY['EMAIL'];
                endif;
                ?>" id="email" name="<?php
                $detailinputname = array('name' => "EMAIL", 'title' => "ایمیل شرکت", 'required' => 0);
                echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>" placeholder="آدرس ایمیل را وارد کنید">
            </div>
        </div>
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <fieldset style="border:solid 1px gray">
                <legend style="border: solid 1px gray;
                                background: gray;
                                font-family: BTitr;
                                font-size: 20px;">آدرس</legend>

                <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
                    <div class="form-group">
                        <label for="stateid">استان <span class="required">*</span></label>
                        <select class="form-control"  id="stateid" name="<?php
                        $detailinputname = array(
                            'name' => "PROVINCE",
                            'title' => "استان محل سکونت ",
                            'required' => 1,
                            'encrypt' => 1
                        );
                        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                        ?>" required='required' placeholder="استان محل سکونت را وارد کنید">
                            <option></option>
                            <?php
                            $companyProvince=base64_encode(Application_Model_Func_Crypt::Encrypt($this->COMPANY['PROVINCE']));
                            foreach ($this->provinces as $province) {
                                ?>
                                <option <?php
                                if ( $companyProvince== $province['CODE']) {
                                    echo "selected";
                                }
                                ?>
                                    value='<?php echo $province['CODE'] ?>'><?php echo $province['CATNAME'] ?>
                                </option>
                                <?php
                            }
                            ?>

                        </select>
                    </div>
                </div>
                <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
                    <div class="form-group">
                        <label for="cityid">شهرستان <span class="required">*</span></label>
                        <select type="text" class="form-control"  id="cityid" name="<?php
                        $detailinputname = array('name' => "CITY", 'title' => "شهرستان محل سکونت ", 'required' => 1, 'encrypt' => 1);
                        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                        ?>" required='required' placeholder="شهرستان محل سکونت را وارد کنید">
                            <option>
                            </option>
                        </select>
                    </div>
                </div>
                <div class="col-xs-10 col-sm-10 col-md-5 col-lg-5">
                    <div class="form-group">
                        <label for="codepost">کد پستی <span class="required">*</span></label>
                        <input type="text" class="form-control" value="<?php
                        if (isset($this->COMPANY)):
                            echo $this->COMPANY['POSTCODE'];
                        endif;
                        ?>" id="codepost" name="<?php
                        $detailinputname = array('name' => "POSTCODE", 'title' => "کدپستی را وارد کنید", 'required' => 1);
                        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                        ?>" required='required' placeholder="کدپستی را وارد کنید">
                    </div>
                </div>
                <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
                    <div class="form-group">
                        <label for="address">آدرس <span class="required">*</span></label>
                        <input type="text" class="form-control" value="<?php
                        if (isset($this->COMPANY)):
                            echo $this->COMPANY['ADDRTEXT'];
                        endif;
                        ?>" id="address" name="<?php
                        $detailinputname = array('name' => "ADDRTEXT", 'title' => "ادرس شرکت", 'required' => 1);
                        echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                        ?>" required='required' placeholder="آدرس را وارد کنید">
                    </div>
                </div>
            </fieldset>
        </div>


    </div>

</form>
<script>
    function getData( $province){
        var optionList = [];
            var companycity='<?php echo base64_encode(Application_Model_Func_Crypt::Encrypt($this->COMPANY['CITY']));?>';
            var selected='';
            $.post('<?php echo $this->baseUrl() ?>/Coding/Mngcoding/getcity', { 'province': $province}, function (result, status) {
                $('#cityid').find('option').remove();
                $.each(result, function (index, elm) {
                    if(elm['SUBCODE']==companycity){
                        selected='selected';
                    }
                    else{
                        selected=''; 
                    }
                    $('#cityid').find('option').end().append('<option '+selected+' value="' + elm['SUBCODE'] + '">' + elm['SUBCATNAME'] + '</option>');
                });
            }, 'json');
    }
    $(document).ready(function () {
        var province='<?php echo base64_encode(Application_Model_Func_Crypt::Encrypt($this->COMPANY['PROVINCE']))?>';
        if(province!=''){
            getData(province);
        }
        $('#stateid').on('change', function () {
           getData($(this).val());
        });
        $('*[required]').attr('oninvalid', "this.setCustomValidity('این فیلد نباید خالی باشد.')");
        $('*[required]').attr('oninput', "this.setCustomValidity('')");

    });
</script>