<div class="modal w-lg fade light blur " id="addCompanyModal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content card shade">
            <div class="modal-header">
                <h5 class="modal-title titr" id="exampleModalLabel">افزودنمشخصات شرکتی جدید</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="" id="contentModal">

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn outlined o-danger c-danger" data-dismiss="modal">بستن</button>

            </div>
        </div>
    </div>
</div>
<div class="modal w-lg fade light blur " id="editCompanyModal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content card shade">
            <div class="modal-header">
                <h5 class="modal-title titr" id="exampleModalLabel">ویرایشمشخصات شرکتی</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="" id="contentModalEdit">

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn outlined o-danger c-danger" data-dismiss="modal">بستن</button>
            </div>
        </div>
    </div>
</div>
<table class="table table-striped table-bordered datatbl" id="companyTbl" style="width:100%">
    <thead>
        <tr>
            <th>ردیف</th>
            <th>انتخاب</th>
            <th>نام شرکت</th>
            <th>تلفن</th>
            <th>آدرس</th>

        </tr>
    </thead>
    <tbody>

    </tbody>

</table>
<script>
    function deletemodal() {
        if ($(':radio[name="choicedcompany"]').is(':checked')) {
 
            bootbox.confirm({
                message: "  برای حذف مطمئن هستید؟", locale: 'fa', callback: function (result) {
                    if (result) {
                        $.ajax({
                            url: "/User/Mngcompany/deletecompany",
                            method: "POST",
                            data: {'<?php
                  $detailinputname = array ('name' => "ID_COMPANY", 'title' => "انتخاب شرکت", 'required' => 1,'encrypt' => 1);
                 echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>': $(':radio[name="choicedcompany"]:checked').val() },
                        })
                            .done(function (res) {
                                var result=JSON.parse(res);
                                if(result.flag){
                                    toastr.success(result.msg, "عملیات حذف شرکت ", { timeOut: 10000 });
                                    var table = $('#companyTbl').DataTable().ajax.reload();
                                }
                                else{
                                    toastr.error(result.msg, "عملیات حذف شرکت ", { timeOut: 10000 });
                                }                       

                            });
                    }
                }
            });

        }
        else {
            bootbox.alert({ message: 'شرکت مورد نظر برای حذف را انتخاب کنید', locale: 'fa' });
        }
    }
    $(document).ready(function () {
        $('.datatbl').DataTable(
            {
                "language":
                {
                    url: '/dist/fa.json',
                },
                processing: true,
                serverSide: true,
                autowidth: false,
                columns: [
                    { "width": "80px" },
                    { "width": "80px" },
                    null, null, null, 
                ],
                ajax: {
                    url:'<?php echo $this->baseUrl() ?>/User/Mngcompany/getcompanylist',
                    error:function(xhr,error,thrown){
                                    toastr.error('خطا در دریافت اطلاعات پیش آمده است لطفا با پشتیبانی تماس بگیرید.', 'خطا در سمت سرور', { timeOut: 50000 });
                            }
                        },
                paging: true,
                lengthMenu: [[5, 10, 20, -1], [5, 10, 20, 'همه']],
            });
        $('#addCompanyModal').on('show.bs.modal', function () {
            GetContent('<?php echo $this->baseUrl() ?>/User/Mngcompany/Addcompany', '#contentModal');

        });
        $('#editCompanyModal').on('show.bs.modal', function (e) {
            if ($(':radio[name="choicedcompany"]').is(":checked")) {
                GetContent('<?php echo $this->baseUrl() ?>/User/Mngcompany/editcompany', '#contentModalEdit',
                 {'<?php
                  $detailinputname = array ('name' => "ID_COMPANY", 'title' => "انتخاب شرکت", 'required' => 1,'encrypt' => 1);
                 echo base64_encode(Application_Model_Func_Crypt::Encrypt(json_encode($detailinputname)));
                ?>': $(':radio[name="choicedcompany"]:checked').val()
                 }
                );
            }
            else {
                $('#contentModalEdit').html('<span class="alert alert-warning">شرکت مورد نظر برای ویرایش را انتخاب کنید</span>');
            }

        });

    });
</script>